#ifndef H_COMPONENT_TYPES
#define H_COMPONENT_TYPES

#include "ruru/components/ComponentTypes.h"

#define COMPONENT_TYPE_POSITION 			0
#define COMPONENT_TYPE_RENDER 				1
#define COMPONENT_TYPE_PLAYER_CONTROL 		2
#define COMPONENT_TYPE_PHYSICS				3
#define COMPONENT_TYPE_BOUNDRY_CHECK		4
#define COMPONENT_TYPE_COLLISION			5
#define COMPONENT_TYPE_SHOOTING				6
#define COMPONENT_TYPE_DAMAGE_DEALING		7
#define COMPONENT_TYPE_DAMAGEABLE			8
#define COMPONENT_TYPE_ENTITY_IDENTIFIER 	9
#define COMPONENT_TYPE_BUFFABLE				10

#endif
